# yaml-language-server: $schema=<https://canary.uniform.app/schemas/json-schema/component-definition/v1.json>
$schema: https://canary.uniform.app/schemas/json-schema/component-definition/v1.json
id: productInfo
name: Product Info
icon: >-
  https://res.cloudinary.com/uniform-demos/image/upload/v1692281207/csk-icons/component-icons-v2/CSKicon_hero_odv0f6_ipen7r.svg
parameters:
  - id: product
    name: Product
    type: json
    helpText: ''
    typeConfig: {}
  - id: group_content
    name: Content
    type: group
    typeConfig:
      collapsed: false
      childrenParams:
        - eyebrowText
        - title
        - titleStyle
        - subTitle
        - description
        - highlightText
        - image
        - features
  - id: eyebrowText
    name: Eyebrow text
    type: text
    helpText: ''
    typeConfig: null
  - id: title
    name: Title
    type: text
    helpText: ''
    typeConfig:
      required: false
      multiline: true
      linesCount: '3'
  - id: titleStyle
    name: Title Style
    type: tp-title-style-parameter
    helpText: ''
    typeConfig: null
  - id: subTitle
    name: Sub Title
    type: text
    helpText: ''
    typeConfig: null
  - id: description
    name: Description
    type: text
    helpText: ''
    typeConfig:
      required: false
      multiline: true
      linesCount: '10'
  - id: highlightText
    name: Highlight Text
    type: text
    helpText: ''
    typeConfig: null
  - id: image
    name: Image
    type: image
    helpText: ''
    typeConfig: null
  - id: features
    name: Features
    type: json
    helpText: ''
    typeConfig:
      schema:
        type: array
        items:
          type: string
  - id: group_primaryCta
    name: Primary CTA
    type: group
    typeConfig:
      childrenParams:
        - primaryButtonCopy
        - primaryButtonStyle
        - primaryButtonLink
        - primaryButtonAnimationType
  - id: primaryButtonCopy
    name: Primary Button Copy
    type: text
    helpText: ''
    typeConfig: null
  - id: primaryButtonStyle
    name: Primary Button Style
    type: tp-button-style-parameter
    helpText: ''
    typeConfig: null
  - id: primaryButtonLink
    name: Primary Button Link
    type: link
    helpText: ''
    typeConfig: null
  - id: primaryButtonAnimationType
    name: Primary Button Animation Type
    type: select
    helpText: ''
    typeConfig:
      options:
        - text: Static
          value: static
        - text: Dynamic
          value: dynamic
  - id: group_secondaryCta
    name: Secondary CTA
    type: group
    typeConfig:
      childrenParams:
        - secondaryButtonCopy
        - secondaryButtonStyle
        - secondaryButtonLink
        - secondaryButtonAnimationType
  - id: secondaryButtonCopy
    name: Secondary Button Copy
    type: text
    helpText: ''
    typeConfig: null
  - id: secondaryButtonStyle
    name: Secondary Button Style
    type: tp-button-style-parameter
    helpText: ''
    typeConfig: null
  - id: secondaryButtonLink
    name: Secondary Button Link
    type: link
    helpText: ''
    typeConfig: null
  - id: secondaryButtonAnimationType
    name: Secondary Button Animation Type
    type: select
    helpText: ''
    typeConfig:
      options:
        - text: Static
          value: static
        - text: Dynamic
          value: dynamic
  - id: group_imageSettings
    name: Image Settings
    type: group
    typeConfig:
      collapsed: true
      childrenParams:
        - objectFit
        - overlayColor
        - overlayOpacity
  - id: objectFit
    name: Object Fit
    type: select
    helpText: ''
    typeConfig:
      options:
        - text: Contain
          value: contain
        - text: Cover
          value: cover
        - text: Fill
          value: fill
        - text: None
          value: none
  - id: overlayColor
    name: Overlay Color
    type: tp-color-style-parameter
    helpText: ''
    typeConfig: null
  - id: overlayOpacity
    name: Overlay Opacity
    type: tp-slider-parameter
    helpText: ''
    typeConfig:
      step: 10
      type: steps
      unit: px
      units: '%'
      options: []
      maxValue: 100
      minValue: 0
  - id: group_presentationSettings
    name: Presentation Settings
    type: group
    typeConfig:
      collapsed: true
      childrenParams:
        - fullHeight
  - id: fullHeight
    name: Full Height
    type: checkbox
    helpText: ''
    typeConfig: null
  - id: group_animationSettings
    name: Animation Settings
    type: group
    typeConfig:
      collapsed: true
      childrenParams:
        - animationType
        - duration
        - oneByOneAnimation
  - id: animationType
    name: Animation Type
    type: select
    helpText: ''
    typeConfig:
      options:
        - text: Static
          value: static
        - text: Dynamic
          value: dynamic
  - id: duration
    name: Duration
    type: select
    helpText: ''
    typeConfig:
      options:
        - text: Slow
          value: slow
        - text: Medium
          value: medium
        - text: Fast
          value: fast
  - id: oneByOneAnimation
    name: One by One Animation
    type: checkbox
    helpText: ''
    typeConfig: null
categoryId: 2da8c924-14d5-470b-9fe4-1e56521551e5
previewImageUrl: >-
  https://res.cloudinary.com/uniform-demos/image/upload/v1/csk-preview-images/UniformTheme/Product_Info_preview_image
useTeamPermissions: true
slots: []
titleParameter: title
canBeComposition: false
created: '2023-09-04T19:16:21.62694+00:00'
updated: '2023-09-21T13:59:23.254075+00:00'
